//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

public class CrashSound : MonoBehaviour {
	
	public AudioClip crashSoft;
	public AudioClip crashHard;

	
	public AudioSource source;
	private float lowPitchRange = .75F;
	private float highPitchRange = 1.5F;
	private float velToVol = .2F;
	private float velocityClipSplit = 10F;
	
	
	void Awake () {
		
		source = GetComponent<AudioSource>();
	}
	
	
	void OnCollisionEnter (Collision coll)
	{
		source.pitch = Random.Range (lowPitchRange,highPitchRange);
		Debug.Log ("make sound");

		float hitVol = coll.relativeVelocity.magnitude * velToVol;
		if (coll.relativeVelocity.magnitude < velocityClipSplit)
			source.PlayOneShot(crashSoft,hitVol);
		    
		else 
			source.PlayOneShot(crashHard,hitVol);
	
	}
	
}
